package util;

public enum Error {
    INVALID_CAPACITY, VENUE_NOT_AVAILABLE, INVALID_VENUE_DESCRIPTION,
    INVALID_ZIP, INVALID_REGION,INVALID_COUNTRY, INVALID_FIRSTNAME,
    INVALID_LASTNAME, INVALID_EMAIL, INVALID_PASSWORD, INVALID_USERNAME,
    INVALID_PHONE
}
